-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 10, 2018 at 10:23 AM
-- Server version: 5.7.14
-- PHP Version: 5.6.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `ippi_project`
--

-- --------------------------------------------------------

--
-- Table structure for table `jobs`
--

CREATE TABLE `jobs` (
  `id` int(11) NOT NULL,
  `web-scraper-order` varchar(255) DEFAULT NULL,
  `web-scraper-start-url` varchar(255) DEFAULT NULL,
  `job` varchar(255) DEFAULT NULL,
  `job_href` varchar(255) DEFAULT NULL,
  `job_title` varchar(255) DEFAULT NULL,
  `job description` varchar(2008) DEFAULT NULL,
  `requirements` varchar(969) NOT NULL,
  `locations` varchar(255) NOT NULL,
  `salary` varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `jobs`
--

INSERT INTO `jobs` (`id`, `web-scraper-order`, `web-scraper-start-url`, `job`, `job_href`, `job_title`, `job description`, `requirements`, `locations`, `salary`) VALUES
(2, '1538458409-2', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analyst', 'https://www.jobstreet.com.my/en/job/data-analyst-3754346?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=16', 'Data Analyst', 'Validating and processing raw data for market research projects. \n	Data checking, data validation and analyzing data in terms of programming and logic.\n	Scripting the computer tables on the requested tabs.\n	Manipulating raw data and provide complex analysis when needed.\n	Manage project task to ensure that deadlines are met and standards are achieved.\n	Providing insight and recommendations on the project to researchers.\n	Explaining data and methods to researchers.\n	Problem solving on issues arising.\n	Managing and interacting with overseas agencies.​', 'Bachelor\'s Degree in Mathematics/Statistics or equivalent.\n	At least 2 years experience in  data analysis preferably in market research industry. \n	Possess knowledge and experience in SPSS Dimensions and/or MrStudio and programming languagues..\n	Excellent skills in Microsoft Office Excel and in VBA\n	Good communication and organisational skills.\n	Possess good problem solving, analytical and has numerical skills.\n	Ability to uinderstand databases\n	Excellent attention to details and meticulous.', 'B-10-01, Level 10, Block B East, PJ8, No. 23, Jalan Barat, Seksyen 8, 46050 Petaling Jaya, Selangor Darul Ehsan', 'Around expected salary'),
(3, '1538458416-5', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Senior Data Analyst', 'https://www.jobstreet.com.my/en/job/senior-data-analyst-3755498?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=13', 'Senior Data Analyst', 'Produce ad hoc reports, trending data, and respond to inquiriesProvide consultation to business leaders on reporting needs, trend analysis and report improvement opportunitiesCoordinate the implementation of reporting processesDevelop BI reports and additions/deletions from existing reports and maintain existing report as well as monthly and year-to-date data summariesUtilize new data sources for report development', 'Minimum Degree in Computer Sciences / Statistics / Actuarial Science or related subjects3-4 years working experienceExpertise in Big Data, particularly with Power BI is a plusStrong in data mining, machine learning, modeling and analyticsStrong MS Office proficiency, programming knowledge in any of the following technologies: SAS, SPSS, R, SQL, Python is advantageDetail-oriented and is a critical thinkerStrong influence and cross-collaborate with other functions by communicating ideas or positions in a persuasive manner that builds support, agreement or commitmentMulti-task, prioritize, and meet timelines on deliverablesWork location: Seri Kembangan, Selangor', 'MUV HQ (Seri Kembangan)\nLot 3, Jalan 6/3\nKawasan Perindustrian Seri Kembangan\n43300 Seri Kembangan\nSelangor', 'null'),
(4, '1538458439-16', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analytics Analysts', 'https://www.jobstreet.com.my/en/job/1', 'null', 'null', 'null', 'null', 'null'),
(5, '1538458441-17', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analytics Analysts', 'https://www.jobstreet.com.my/en/job/data-analytics-analysts-3759482?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=1', 'Data Analytics Analysts', 'null', 'null', 'No. 1, Jalan Pengaturcara U1/51A, Section U1, Kawasan Perindustrian Temasya, 40150 Shah Alam, Selangor, Malaysia', 'null'),
(6, '1538458433-13', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Master Product Data, Senior Analyst', 'https://www.jobstreet.com.my/en/job/master-product-data-senior-analyst-3756392?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=4', 'Master Product Data, Senior Analyst', 'Ensure speed to market for all new products by assigning to the EPH in a timely manner, and enable accurate and insightful reporting and analysis by relevant categorization.Liaise with sales and marketing teams across the region to ensure products are identified correctly and categorized appropriately for planning and reporting needs.Clarify and correct relevant product details such as description and Unit of Measurement (UOM) factors – connecting directly with sales and marketing contacts in country. Drive awareness of standards across these contactsEnsure EPH remains relevant and accurate by delivering active governance against EPH policy, standards and rules.Escalate any business requests that do not conform to EPH policy, standards or rules.Continue to refine the quality of EPH by proposing additions or refinements to EPH policies, standards and rules - at APAC and Enterprise level.Drive awareness of EPH policy, standards and rules across APAC business contacts.Responsible for the ongoing quality of EPH through regular exception reporting and timely remediation of exceptions.Maintain mapping files that link EPH to other hierarchies such as profit center and Anaplan.Proactively engage with country and regional marketing teams to plan ahead for new product introductions and re-launches. Drive alignment across all stakeholders in the categorization and representation of K-C products within EPH.Proactively engage with Management Reporting (MID) and Financial Planning & Analyst (FP&A) teams to ensure the EPH is fully meeting the needs of this communities. It is also essential to drive alignment between these two teams.Be the subject matter expert for EPH, aware of all applications within APAC and the sensitivities around each. Be ready to attend business or IT Services (ITS) meetings to represent EPH within APAC.Deliver regular KPI reporting to the business on the health of EPH in APAC.As part of the APAC Master Data Team provide reciprocal backup of other roles as required.', 'Degree in Business, finance or related field.At least 5 year(s) of working experience in a related field.Must be a self-starter and strong independent worker.Strong communicator with good command of verbal and written English.Proven ability collaborating with cross-functional, cross-regional teams dealing with complex issues.Experience of working with reporting and /or data management software.', 'Wisma AmFirst, Jalan SS7/15, Jalan Stadium, Kelana Jaya, 47301', 'null'),
(7, '1538458428-11', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analyst', 'https://www.jobstreet.com.my/en/job/data-analyst-6782000/origin/sg?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=7', 'Data Analyst', 'Collect, analyze, evaluate and report data in order to increase sales productivityCollect sales records & trends and evaluate performance measured against BudgetAssist in developing models and reporting structure that identify costs (by Area, event, program promotion) and identify a baseline for actionAssist Head of Department in reporting on local incentive with a detailed analysis in supporting business decisionsAssist in developing and reviewing the sales budget and sales forecast including sales to budget variance analysis.Analyze proposal for Sales events.Analyze Sales Promo Program and provide a report to ManagementAssist in compliance matters and company events as and when needed.', 'Degree in Mathematics, Statistics, Economics or equivalentPreferably candidates with knowledge in programming or data miningA great team player with good interpersonal skillsAble to work independently with minimum supervisionGood command of languages to communicate the analysis reports to the relevant parties.Proficient in Microsoft Office Application especially Microsoft Excel and PowerPoint.Knowledge in Statistical Software would be an added advantage.Have an eye for detail with good analytical skillsAt least 1 year of relevant work experiences', 'null', 'Around expected salary'),
(8, '1538458420-7', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analyst', 'https://www.jobstreet.com.my/en/job/data-analyst-3756957?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=11', 'Data Analyst', 'Data Acquisition, Data Quality improvement & Automation – Responsible for overseeing the monthly and weekly process steps to deliver timely, quality data into the GPD and SAP system.Coordinate resolution of data quality issues with local analysts and HR teams (both technical and non-technical people).Liaise with business HR stakeholders to understand and address challenges around data quality and Data loading perspective.', '2+ years of SAP BW or equivalent data modelling experience (Operational management or technical delivery)2+ years of data administration and analysis experience (Focus on Data Quality Assurance)Proven experience in working with large volume of data (HR, Non Financial or Financial) – operating at expert levelStrong relationship management skills with a strong understanding of customers’ needs / behaviours.Rigorous attention to detail, good listening, communication, influencing skills and a self-starter.Strong communicator who can bridge the techno functional gap when communicating with both business and technical stakeholders.Experience in data analysis and report preparation through Excel, including advanced use of Excel functions, VBA.Experience of Data Management, Privacy, Protection & ComplianceApplicants must be willing to work in Bangsar South.Preferably Senior Executives specializing in Human Resources or equivalent.3 Contract position(s) available.', 'Level 1-12, Tower 5, Avenue 7, The Horizon Bangsar South City, No.8, Jalan Kerinchi, 59200 Kuala Lumpur', 'Around expected salary'),
(9, '1538458418-6', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Business Data Analyst II (KL)', 'https://www.jobstreet.com.my/en/job/business-data-analyst-ii-kl-3756043?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=12', 'Business Data Analyst II (KL)', 'Responsible for being an “expert” with Sales Reporting , Point of Sale (POS) & inventory data management from on-boarding to optimization.Work with Zyme Solutions (MSI appointed Contractor) to validate, cleanse, scrub, enrich, and validate POS & Inventory submissions by distributors & proactively seek for scalability improvements regarding data management and data control.Work across channels and functions to deliver reliable and timely information on leading sales indicators (sell-in, sell-thru, inventory and sell-out).Drive sales effectiveness by delivering crucial insights to sales with proactive information delivery (metrics, alerts, analysis, executive and personalized dashboards) that enable the sales teams to assess sales performance, identify early opportunities or risks, improve forecasting accuracy, and address bottlenecks.Responsible for developing reports, both ad hoc and ongoing, that provides the analytics and metrics to support the PartnerEmpower program compliance and governance.Produce assigned dashboards, KPIs, scorecards and excel indicators within required time standards.Prepare, produce, validate and publish monthly, quarterly reports specifically to measure and monitor reseller performance as well as other programs, incentives and promotions.Educate partners on how to leverage data as an asset for their function/ business. Collaborate to understand objectives, identify analysis opportunities, and prioritize projects in order to deliver maximum business impact.Perform Data validation of data to ensure accuracy and quality.Other duties as assignedThis position will be based in Kuala Lumpur.', 'Bachelor\'s degree in business administration or quantitative field with 3-5 years of related experience supporting a sales organization.Business knowledge and experience in sales analytics.Excellent coordination and interpersonal skills, team player with the ability to work effectively with all levels of organization.Strong financial and business acumen.Knowledge of Business Intelligence tools is desirable.Advanced MS Excel experience.Preferably able to communicate fluently in Chinese and English.Self-motivated and can take ownership and initiativeModerate level of knowledge of inventory analysis.Possess Solid Understanding of Sales Reporting Framework.Excellent communication, presentation, and collaboration skillsMust be willing to work in Kuala Lumpur.', 'Plot 2A, Medan Bayan Lepas, MUKIM 12, S.W.D, 11900 Bayan Lepas, Penang, Malaysia.', 'null'),
(10, '1538458407-1', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Manager, Campaign Management (Data Analyst under Decision Management)', 'https://www.jobstreet.com.my/en/job/manager-campaign-management-data-analyst-under-decision-management-3753360?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=20', 'Manager, Campaign Management (Data Analyst under Decision Management)', 'Support end-to-end campaign management (product & data driven), by providing pre-campaign analysis, post campaign analysis to track success of campaign and channel performance, provide closed-loop feedback and recommendation for future campaigns, towards enlarging the customer base via behavioral marketing analytics throughout entire customer life cycle management.Develop script for target-based and event-triggered campaign, manage customer contact (contact policy and leads historical base), supporting coordinate / plan roll-out of all databased campaign and prospect leads to sales channel.Work with business and risk management to develop credit portfolio and test program.Participate in process improvement and technology enablement in the area of productivity and security.Maximize franchise linkage with joint collaboration between LOBs and enhanced KPIs. Sequential increase in penetration of Consumer Banking relationship among business owner and employees.', 'Experience in technical and business analytics environment of at least 2 to 4 years would be a plus pointAnalytical, logical, strategic thinking and excellent executorExcellent analytical based  statistical applications and methodologiesFully understand the Business Intelligence solution suites to craft best in class information delivery platformData warehouse technical architectureRelational database managementBusiness intelligence exploratory and visualization capabilitiesSolid experience in banking operations, MIS system management and database marketingGreat awareness of Commercial and Investment Banking products and market trends', 'Menara Multi Purpose, Jalan Munshi Abdullah, Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur, Malaysia', 'null'),
(11, '1538458437-15', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Risk Data Analyst', 'https://www.jobstreet.com.my/en/job/risk-data-analyst-3759407?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=2', 'Risk Data Analyst', 'Responsible for maintenance of business intelligence applications.\n	\n	\n	Facilitates organizational data strategies for governance, design, implementation, integration and usage.\n	\n	\n	Utilize business data and statistical methods to provide insight into business performance and suggest area for and methods of improving operations.\n	\n	\n	Ensures that the use of business intelligence applications enhance business decision-making capabilities.\n	\n	\n	Provides input to strategic decisions that affect the functional area of responsibility.', 'Candidate must possess at least Bachelor\'s Degree/Post Graduate Diploma/Professional Degree in Computer Science/Information Technology or equivalent.\n	Required Skill(s): Basic knowledge of programming (R, SQL)\n	Any additional professional qualifications will be an added advantage.\n	Fresh graduates are welcome to apply.', 'Level 3A, Tower 6, Avenue 5, The Horizon, No. 8, Jalan Kerinchi, Bangsar South', 'Around expected salary'),
(12, '1538458422-8', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'System & Big Data Analyst', 'https://www.jobstreet.com.my/en/job/system-big-data-analyst-3757088?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=10', 'System & Big Data Analyst', 'null', 'null', 'No.13-02, Jalan 5/20E, Pusat Perdagangan Kota Damansara, Kota Damansara PJU 5, 47810 Petaling Jaya, Selangor.', 'MYR 2,600 - MYR 4,000'),
(13, '1538458426-10', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Senior System Analyst ($8000, BA / SA / SDLC, Data Migration, Remittance)', 'https://www.jobstreet.com.my/en/job/senior-system-analyst-8000-basa-sdlc-data-migration-remittance-6781052/origin/sg?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=8', 'Senior System Analyst ($8000, BA/SA/ SDLC, Data Migration, Remittance)', 'Up to $8000Data Migration experienceBA + SAJapanese IT company', 'Understand the design and functionalities of the system from both Technical and Business perspectives.Play a vital role in steering various test phases of the project towards completion by closely interacting with various stakeholders.Conduct defect and release management with the vendor and internal system teams.Understand and create the Migration Plan of the system. Lead/participate in the migration phase.Review and sign-off the artefacts produced by the vendor.Support the handover and transition to operation teams.Support system UAT and post Go-Live.To ensure successful implementation of the solution.Contributing ResponsibilitiesContribute actively towards planning activities related to future phases of the project.To lead one or more consultants within the team.To share expertise by providing training and knowledge sharing sessions', '146 Robinson Road #08-01 Singapore 068909', 'null'),
(14, '1538458435-14', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'SAS Programmer (Data Analyst)', 'https://www.jobstreet.com.my/en/job/sas-programmer-data-analyst-3758635?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=3', 'SAS Programmer (Data Analyst)', 'Work closely with data warehouse to perform automation using SAS programming for process of improvement of internal routine report generationIdentify and extract relevant fields from the systems to support business decision.Automation of new reporting functions basing on new business structure.Collect and synthesize internal and external data, monitor and manage data sources to ensure data quality and accuracyTo maintain Business Banking database / data mart and provide informational analysis for performance tracking/ marketing/cross selling purposes.Assisting head to attend the information requirements requested by external bodies (e.g. BNM/Auditor/Rating Agency etc.)To build performance dashboard using SAS VA tool', 'Bachelor’s Degree in Computer Science, Statistics, Business, Banking or other related qualificationCandidate must possess at least 5 year experience in MIS, data warehousing, campaign lead generation or Business Intelligence environmentCandidate must possess experience in using SAS Base Programming or SAS Enterprise Guide for at least 3 yearsProficiency in Microsoft ExcelInclination towards analytical type of work with attention to detailsIndependent, strong problem solving, analytical and enjoys data explorationAbility to work with a minimum supervision and manage independently as well as being an effective team player with both internal stakeholders and third parties.Flexible, adaptable and open to the rapid changes in job requirementsAble to work under pressure, meet short deadlines and work extra hours if needed', 'Rhb Centre Jalan Tun Razak Kuala Lumpur Selangor Malaysia', 'null'),
(15, '1538458411-3', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analyst & Audit (Junior Executive)', 'https://www.jobstreet.com.my/en/job/data-analyst-audit-junior-executive-3754784?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=15', 'Data Analyst & Audit (Junior Executive)', 'Validating and processing raw data for audit and research purpose.Data checking, data validation and analysing data in terms of programming and logicScripting the computer tables on the requested tabsManipulating raw data and provide complex analysis when neededExplaining data and methods to managementProblem solving on issues arisingManage project task to ensure that deadlines are met and standards are achieved', 'Bachelor’s Degree in Mathematics/Statistics or equivalentFresh graduates are encouraging to apply.Excellent skills in Microsoft Office Excel and in VBAGood communication and organisational skills, MandarinPossess good problems solving, analytical and has numerical skillsExcellent attention to details and meticulous.', 'C-21-1, KL Trillion, 338, Jalan Tun Razak, 50400 Kuala Lumpur', 'MYR 2,700 - MYR 3,800'),
(16, '1538458424-9', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Data Analyst', 'https://www.jobstreet.com.my/en/job/data-analyst-6781081/origin/sg?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=9', 'Data Analyst', 'Process new lead information according to the project , prepare lead data to be used by telemarketers in securing appointments for clients from various sources, Organize lead information for future use and Ensure there are no duplicates.\n	\n	\n	Filtering of data and data analysis which impacts the quality of leads that the hunters will engage.\n	\n	\n	Identify, analyze, and interpret trends or patterns in complex data sets\n	\n	\n	Develop, maintain data and databases, data collection systems, data analytics and other strategies that optimize statistical efficiency and quality\n	\n	\n	Streamline the data collection process and identify new opportunities for process improvement\n	\n	\n	Lead Generation - Identify Qualification of data and Acquiring data from primary or secondary data sources and maintaining databases\n	\n	\n	Creating a database of people and/or companies that fulfil our client’s criteria for them to be used as leads. This could include going through multiple online sources to find extensive information about leads/competitors.\n	\n	\n	General online research, collecting information about competitors.\n	\n	\n	Content Verification – Validating content provided in order to ensure accuracy and remove inconsistencies.', 'Proven working experience as a data analyst or business data analyst\n	\n	\n	Technical expertise regarding data models, database design development, data mining and segmentation techniques\n	\n	\n	Knowledge of statistics and experience using statistical packages for analyzing datasets (Excel, etc)\n	\n	\n	Strong analytical skills with the ability to collect, organize, analyze, and disseminate significant amounts of information with attention to detail and accuracy\n	\n	\n	Adept at queries, report writing and presenting findings\n	\n	\n	Excellent communication and interpersonal skills\n	\n	\n	An analytical mind and inclination to problem solving\n	\n	\n	Attention to details, and good time management skill\n	\n	\n	Strong analytical skills with eye for detail\n	\n	\n	Highly adaptable and flexible\n	\n	\n	High Integrity & Honest\n	\n	\n	Growth Oriented & Continuous learning mindset\n	\n	\n	Value driven and a team leader and a team player\n	\n	\n	Literally driven by Productivity & Efficiency', 'Kuala Lumpur', 'null'),
(17, '1538458413-4', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Digital Analyst, People Data Centre', 'https://www.jobstreet.com.my/en/job/digital-analyst-people-data-centre-3755018?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=14', 'Digital Analyst, People Data Centre', 'Provide analysis, reporting and insights on cross-channel campaigns and brand performance, often making recommendations for adjustment to marketing campaigns in-flightBuild custom analytics dashboards and reports that can effectively present digital performance to the appropriate audiencesMeasure marketing effectiveness and value of media and web personalisation campaigns, and present actionable insights and recommendations based on data results and best practicesSupport brand teams in the development of measurement plans for campaigns, audiences and A/B testingLeverage data to gain insight into trends, user experience and behaviour in order to drive the appropriate digital marketing, mobile and social strategiesAdvise on creation of use cases and personalised experiences for selected audiencesAdvise the Digital Category Lead, Insight Specialist and CRM Lead on how to optimize their data quality, increasing value to be leveraged for future usageWork with the DMP consultant to brief appropriate audience selections for Media and web personalization campaignsExpert and go-to person on Adobe Analytics and Adobe Target towards brands and brand execution teamsCoordinate the execution of A/B tests, analyse test results for presentation to stakeholders and do in-flight reporting on the performanceWork in close collaboration with media agencies to determine which media needs to be tagged, which data needs to be collected and how this data can be used in campaignsConstruct test & learn marketing activity and analyse results for presentation to stakeholdersUnderstands the data-model and is responsible for extractions, suppression, advising on how to improve data qualityData analysis of ad hoc requestsSuggest experience optimisation for specific audiences (i.e. serving different content variations per audience to see what works best)Ensuring standardisation, quality and best practices in analysis and reporting.', 'Primary delivery responsibility to both Global Categories and assigned regional (market / cluster) brand teams (squads)Deliver multiple projects simultaneously; time and resource is managed by PDC Delivery Hub ManagerWork with other PDC delivery roles to ensure that all outputs are delivered on-time and in line with internal customer requirements', 'Level 33-35, Menara TM, Jalan Pantai Baru, 59200 Kuala Lumpur', 'null'),
(18, '1538458430-12', 'https://www.jobstreet.com.my/en/job-search/job-vacancy.php?key=data+analyst&location=&specialization=&area=&salary=&ojs=3&src=12', 'Business Analyst / BI / Data Analyst - NO EXPERIENCE REQ / Work in SG', 'https://www.jobstreet.com.my/en/job/business-analyst-bi-data-analyst-no-experience-req-work-in-sg-6782541/origin/sg?fr=21&src=12&searchRequestToken=4d6a7373-db00-4c55-b82e-52f493e067e0&sectionRank=6', 'Business Analyst/ BI/ Data Analyst - NO EXPERIENCE REQ / Work in SG', 'null', 'null', '1 Tampines Central 5 #06-01 CPF Tampines Building Singapore 529508', 'null');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `jobs`
--
ALTER TABLE `jobs`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `jobs`
--
ALTER TABLE `jobs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
